# Generated by Django 4.2.16 on 2026-05-19 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField(blank=True)),
                ('full_content', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('category', models.CharField(choices=[('OpenAI', 'OpenAI'), ('Google', 'Google'), ('Anthropic', 'Anthropic'), ('Meta', 'Meta'), ('DeepSeek', 'DeepSeek'), ('AI Agents', 'AI Agents'), ('Research', 'Research'), ('Startup', 'Startup'), ('Healthcare', 'Healthcare'), ('Robotics', 'Robotics'), ('Tools', 'Tools'), ('General AI', 'General AI')], default='General AI', max_length=50)),
                ('tag', models.CharField(choices=[('NEW', 'New'), ('HOT', 'Hot'), ('TRENDING', 'Trending')], default='NEW', max_length=20)),
                ('importance', models.IntegerField(default=5)),
                ('image_seed', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
